name: Run Scraper Daily

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8:00 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Chrome Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Create credentials file
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          mkdir -p creds
          echo "$GOOGLE_CREDENTIALS" > creds/sptpl-452205-1e66df629e9d.json

      - name: Run scraper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: creds/sptpl-452205-1e66df629e9d.json
        run: |
          python scraper.py
